title: Zhongtian Zhang
url: "https://zhangepl.github.io"
# baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://zhangepl.github.io"
footer_text: "Zhongtian Zhang, Yale University"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "ZZCV.pdf"
 - name: "Publications"
   link: "publications"
